apiVersion: apps/v1
kind: Deployment
metadata: { name: book-svc, namespace: lib-dev }
spec:
  replicas: 1
  selector: { matchLabels: { app: book-svc } }
  template:
    metadata: { labels: { app: book-svc } }
    spec:
      containers:
      - name: app
        image: book-svc:0.1.0
        imagePullPolicy: Never
        ports: [{ containerPort: 3001 }]
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb.lib-dev.svc.cluster.local:27017/books"
        readinessProbe: { httpGet: { path: /health, port: 3001 }, initialDelaySeconds: 5 }
        livenessProbe:  { httpGet: { path: /health, port: 3001 }, initialDelaySeconds: 15 }
---
apiVersion: v1
kind: Service
metadata: { name: book-svc, namespace: lib-dev }
spec:
  selector: { app: book-svc }
  ports: [{ name: http, port: 80, targetPort: 3001 }]
