version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo-service
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s


  user-service:
    build:
      context: ./services/user-services
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
    depends_on:
      - mongo

  borrow-service:
    build:
      context: ./services/borrow-services
    container_name: borrow-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo

volumes:
  mongo_data:
